# SPDX-License-Identifier: MIT
#
# 完全禁用系统级 Suspend/Hibernate/HybridSleep，防止因 SM8550 PCIe/eUSB2 总线
# 挂起失败引发的秒醒弹回与状态机死锁。

[Sleep]
AllowSuspend=no
AllowHibernation=no
AllowSuspendThenHibernate=no
AllowHybridSleep=no
